--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- dbv0_0_39_set_config class
local dbv0_0_39_set_config = {}
local dbv0_0_39_set_config_mt = {
	__name = "dbv0_0_39_set_config";
	__index = dbv0_0_39_set_config;
}

local function cast_dbv0_0_39_set_config(t)
	return setmetatable(t, dbv0_0_39_set_config_mt)
end

local function new_dbv0_0_39_set_config(clusters, TRES, accounts, users, qos, wckeys, associations)
	return cast_dbv0_0_39_set_config({
		["clusters"] = clusters;
		["TRES"] = TRES;
		["accounts"] = accounts;
		["users"] = users;
		["qos"] = qos;
		["wckeys"] = wckeys;
		["associations"] = associations;
	})
end

return {
	cast = cast_dbv0_0_39_set_config;
	new = new_dbv0_0_39_set_config;
}
