--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- dbv0_0_39_response_associations_delete class
local dbv0_0_39_response_associations_delete = {}
local dbv0_0_39_response_associations_delete_mt = {
	__name = "dbv0_0_39_response_associations_delete";
	__index = dbv0_0_39_response_associations_delete;
}

local function cast_dbv0_0_39_response_associations_delete(t)
	return setmetatable(t, dbv0_0_39_response_associations_delete_mt)
end

local function new_dbv0_0_39_response_associations_delete(meta, errors, warnings, removed_associations)
	return cast_dbv0_0_39_response_associations_delete({
		["meta"] = meta;
		["errors"] = errors;
		["warnings"] = warnings;
		["removed_associations"] = removed_associations;
	})
end

return {
	cast = cast_dbv0_0_39_response_associations_delete;
	new = new_dbv0_0_39_response_associations_delete;
}
