--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- dbv0_0_39_meta_slurm class
local dbv0_0_39_meta_slurm = {}
local dbv0_0_39_meta_slurm_mt = {
	__name = "dbv0_0_39_meta_slurm";
	__index = dbv0_0_39_meta_slurm;
}

local function cast_dbv0_0_39_meta_slurm(t)
	return setmetatable(t, dbv0_0_39_meta_slurm_mt)
end

local function new_dbv0_0_39_meta_slurm(version, release)
	return cast_dbv0_0_39_meta_slurm({
		["version"] = version;
		["release"] = release;
	})
end

return {
	cast = cast_dbv0_0_39_meta_slurm;
	new = new_dbv0_0_39_meta_slurm;
}
