--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- dbv0_0_39_diag class
local dbv0_0_39_diag = {}
local dbv0_0_39_diag_mt = {
	__name = "dbv0_0_39_diag";
	__index = dbv0_0_39_diag;
}

local function cast_dbv0_0_39_diag(t)
	return setmetatable(t, dbv0_0_39_diag_mt)
end

local function new_dbv0_0_39_diag(meta, errors, warnings, statistics)
	return cast_dbv0_0_39_diag({
		["meta"] = meta;
		["errors"] = errors;
		["warnings"] = warnings;
		["statistics"] = statistics;
	})
end

return {
	cast = cast_dbv0_0_39_diag;
	new = new_dbv0_0_39_diag;
}
