--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- dbv0_0_39_error class
local dbv0_0_39_error = {}
local dbv0_0_39_error_mt = {
	__name = "dbv0_0_39_error";
	__index = dbv0_0_39_error;
}

local function cast_dbv0_0_39_error(t)
	return setmetatable(t, dbv0_0_39_error_mt)
end

local function new_dbv0_0_39_error(error_number, error, source, description)
	return cast_dbv0_0_39_error({
		["error_number"] = error_number;
		["error"] = error;
		["source"] = source;
		["description"] = description;
	})
end

return {
	cast = cast_dbv0_0_39_error;
	new = new_dbv0_0_39_error;
}
