--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- dbv0_0_39_update_users class
local dbv0_0_39_update_users = {}
local dbv0_0_39_update_users_mt = {
	__name = "dbv0_0_39_update_users";
	__index = dbv0_0_39_update_users;
}

local function cast_dbv0_0_39_update_users(t)
	return setmetatable(t, dbv0_0_39_update_users_mt)
end

local function new_dbv0_0_39_update_users(users)
	return cast_dbv0_0_39_update_users({
		["users"] = users;
	})
end

return {
	cast = cast_dbv0_0_39_update_users;
	new = new_dbv0_0_39_update_users;
}
