--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes class
local v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes = {}
local v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes_mt = {
	__name = "v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes";
	__index = v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes;
}

local function cast_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes_mt)
end

local function new_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes(per)
	return cast_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes({
		["per"] = per;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes;
	new = new_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_tres_minutes;
}
