--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job_reservation class
local v0_0_39_job_reservation = {}
local v0_0_39_job_reservation_mt = {
	__name = "v0_0_39_job_reservation";
	__index = v0_0_39_job_reservation;
}

local function cast_v0_0_39_job_reservation(t)
	return setmetatable(t, v0_0_39_job_reservation_mt)
end

local function new_v0_0_39_job_reservation(id, name)
	return cast_v0_0_39_job_reservation({
		["id"] = id;
		["name"] = name;
	})
end

return {
	cast = cast_v0_0_39_job_reservation;
	new = new_v0_0_39_job_reservation;
}
