--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_wckey_tag class
local v0_0_39_wckey_tag = {}
local v0_0_39_wckey_tag_mt = {
	__name = "v0_0_39_wckey_tag";
	__index = v0_0_39_wckey_tag;
}

local function cast_v0_0_39_wckey_tag(t)
	return setmetatable(t, v0_0_39_wckey_tag_mt)
end

local function new_v0_0_39_wckey_tag(wckey, flags)
	return cast_v0_0_39_wckey_tag({
		["wckey"] = wckey;
		["flags"] = flags;
	})
end

return {
	cast = cast_v0_0_39_wckey_tag;
	new = new_v0_0_39_wckey_tag;
}
