--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_process_exit_code_verbose_signal class
local v0_0_40_process_exit_code_verbose_signal = {}
local v0_0_40_process_exit_code_verbose_signal_mt = {
	__name = "v0_0_40_process_exit_code_verbose_signal";
	__index = v0_0_40_process_exit_code_verbose_signal;
}

local function cast_v0_0_40_process_exit_code_verbose_signal(t)
	return setmetatable(t, v0_0_40_process_exit_code_verbose_signal_mt)
end

local function new_v0_0_40_process_exit_code_verbose_signal(id, name)
	return cast_v0_0_40_process_exit_code_verbose_signal({
		["id"] = id;
		["name"] = name;
	})
end

return {
	cast = cast_v0_0_40_process_exit_code_verbose_signal;
	new = new_v0_0_40_process_exit_code_verbose_signal;
}
