--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_step_statistics_cpu class
local v0_0_39_step_statistics_cpu = {}
local v0_0_39_step_statistics_cpu_mt = {
	__name = "v0_0_39_step_statistics_cpu";
	__index = v0_0_39_step_statistics_cpu;
}

local function cast_v0_0_39_step_statistics_cpu(t)
	return setmetatable(t, v0_0_39_step_statistics_cpu_mt)
end

local function new_v0_0_39_step_statistics_cpu(actual_frequency)
	return cast_v0_0_39_step_statistics_cpu({
		["actual_frequency"] = actual_frequency;
	})
end

return {
	cast = cast_v0_0_39_step_statistics_cpu;
	new = new_v0_0_39_step_statistics_cpu;
}
