--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_users_add_cond class
local v0_0_40_users_add_cond = {}
local v0_0_40_users_add_cond_mt = {
	__name = "v0_0_40_users_add_cond";
	__index = v0_0_40_users_add_cond;
}

local function cast_v0_0_40_users_add_cond(t)
	return setmetatable(t, v0_0_40_users_add_cond_mt)
end

local function new_v0_0_40_users_add_cond(accounts, association, clusters, partitions, users, wckeys)
	return cast_v0_0_40_users_add_cond({
		["accounts"] = accounts;
		["association"] = association;
		["clusters"] = clusters;
		["partitions"] = partitions;
		["users"] = users;
		["wckeys"] = wckeys;
	})
end

return {
	cast = cast_v0_0_40_users_add_cond;
	new = new_v0_0_40_users_add_cond;
}
