--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job class
local v0_0_39_job = {}
local v0_0_39_job_mt = {
	__name = "v0_0_39_job";
	__index = v0_0_39_job;
}

local function cast_v0_0_39_job(t)
	return setmetatable(t, v0_0_39_job_mt)
end

local function new_v0_0_39_job(account, comment, allocation_nodes, array, association, block, cluster, constraints, container, derived_exit_code, time, exit_code, extra, failed_node, flags, group, het, job_id, name, licenses, mcs, nodes, partition, hold, priority, qos, required, kill_request_user, reservation, script, state, steps, submit_line, tres, used_gres, user, wckey, working_directory)
	return cast_v0_0_39_job({
		["account"] = account;
		["comment"] = comment;
		["allocation_nodes"] = allocation_nodes;
		["array"] = array;
		["association"] = association;
		["block"] = block;
		["cluster"] = cluster;
		["constraints"] = constraints;
		["container"] = container;
		["derived_exit_code"] = derived_exit_code;
		["time"] = time;
		["exit_code"] = exit_code;
		["extra"] = extra;
		["failed_node"] = failed_node;
		["flags"] = flags;
		["group"] = group;
		["het"] = het;
		["job_id"] = job_id;
		["name"] = name;
		["licenses"] = licenses;
		["mcs"] = mcs;
		["nodes"] = nodes;
		["partition"] = partition;
		["hold"] = hold;
		["priority"] = priority;
		["qos"] = qos;
		["required"] = required;
		["kill_request_user"] = kill_request_user;
		["reservation"] = reservation;
		["script"] = script;
		["state"] = state;
		["steps"] = steps;
		["submit_line"] = submit_line;
		["tres"] = tres;
		["used_gres"] = used_gres;
		["user"] = user;
		["wckey"] = wckey;
		["working_directory"] = working_directory;
	})
end

return {
	cast = cast_v0_0_39_job;
	new = new_v0_0_39_job;
}
