--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_assoc class
local v0_0_39_assoc = {}
local v0_0_39_assoc_mt = {
	__name = "v0_0_39_assoc";
	__index = v0_0_39_assoc;
}

local function cast_v0_0_39_assoc(t)
	return setmetatable(t, v0_0_39_assoc_mt)
end

local function new_v0_0_39_assoc(account, cluster, default, flags, max, is_default, min, parent_account, partition, priority, qos, shares_raw, usage, user)
	return cast_v0_0_39_assoc({
		["account"] = account;
		["cluster"] = cluster;
		["default"] = default;
		["flags"] = flags;
		["max"] = max;
		["is_default"] = is_default;
		["min"] = min;
		["parent_account"] = parent_account;
		["partition"] = partition;
		["priority"] = priority;
		["qos"] = qos;
		["shares_raw"] = shares_raw;
		["usage"] = usage;
		["user"] = user;
	})
end

return {
	cast = cast_v0_0_39_assoc;
	new = new_v0_0_39_assoc;
}
