--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_job_required class
local v0_0_40_job_required = {}
local v0_0_40_job_required_mt = {
	__name = "v0_0_40_job_required";
	__index = v0_0_40_job_required;
}

local function cast_v0_0_40_job_required(t)
	return setmetatable(t, v0_0_40_job_required_mt)
end

local function new_v0_0_40_job_required(cpus, memory_per_cpu, memory_per_node)
	return cast_v0_0_40_job_required({
		["CPUs"] = cpus;
		["memory_per_cpu"] = memory_per_cpu;
		["memory_per_node"] = memory_per_node;
	})
end

return {
	cast = cast_v0_0_40_job_required;
	new = new_v0_0_40_job_required;
}
