--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_partition_resp_partitions_inner_timeouts class
local v0_0_41_openapi_partition_resp_partitions_inner_timeouts = {}
local v0_0_41_openapi_partition_resp_partitions_inner_timeouts_mt = {
	__name = "v0_0_41_openapi_partition_resp_partitions_inner_timeouts";
	__index = v0_0_41_openapi_partition_resp_partitions_inner_timeouts;
}

local function cast_v0_0_41_openapi_partition_resp_partitions_inner_timeouts(t)
	return setmetatable(t, v0_0_41_openapi_partition_resp_partitions_inner_timeouts_mt)
end

local function new_v0_0_41_openapi_partition_resp_partitions_inner_timeouts(resume, suspend)
	return cast_v0_0_41_openapi_partition_resp_partitions_inner_timeouts({
		["resume"] = resume;
		["suspend"] = suspend;
	})
end

return {
	cast = cast_v0_0_41_openapi_partition_resp_partitions_inner_timeouts;
	new = new_v0_0_41_openapi_partition_resp_partitions_inner_timeouts;
}
