--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_license class
local v0_0_39_license = {}
local v0_0_39_license_mt = {
	__name = "v0_0_39_license";
	__index = v0_0_39_license;
}

local function cast_v0_0_39_license(t)
	return setmetatable(t, v0_0_39_license_mt)
end

local function new_v0_0_39_license(license_name, total, used, free, remote, reserved, last_consumed, last_deficit, last_update)
	return cast_v0_0_39_license({
		["LicenseName"] = license_name;
		["Total"] = total;
		["Used"] = used;
		["Free"] = free;
		["Remote"] = remote;
		["Reserved"] = reserved;
		["LastConsumed"] = last_consumed;
		["LastDeficit"] = last_deficit;
		["LastUpdate"] = last_update;
	})
end

return {
	cast = cast_v0_0_39_license;
	new = new_v0_0_39_license;
}
