--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_rollup_stats_inner class
local v0_0_40_rollup_stats_inner = {}
local v0_0_40_rollup_stats_inner_mt = {
	__name = "v0_0_40_rollup_stats_inner";
	__index = v0_0_40_rollup_stats_inner;
}

local function cast_v0_0_40_rollup_stats_inner(t)
	return setmetatable(t, v0_0_40_rollup_stats_inner_mt)
end

local function new_v0_0_40_rollup_stats_inner(type, last_run, max_cycle, total_time, total_cycles, mean_cycles)
	return cast_v0_0_40_rollup_stats_inner({
		["type"] = type;
		["last run"] = last_run;
		["max_cycle"] = max_cycle;
		["total_time"] = total_time;
		["total_cycles"] = total_cycles;
		["mean_cycles"] = mean_cycles;
	})
end

return {
	cast = cast_v0_0_40_rollup_stats_inner;
	new = new_v0_0_40_rollup_stats_inner;
}
