--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner class
local v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner = {}
local v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner_mt = {
	__name = "v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner";
	__index = v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner;
}

local function cast_v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner_mt)
end

local function new_v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner(account, cluster, partition, user, id)
	return cast_v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner({
		["account"] = account;
		["cluster"] = cluster;
		["partition"] = partition;
		["user"] = user;
		["id"] = id;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner;
	new = new_v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner;
}
