--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_assoc_rec_set class
local v0_0_40_assoc_rec_set = {}
local v0_0_40_assoc_rec_set_mt = {
	__name = "v0_0_40_assoc_rec_set";
	__index = v0_0_40_assoc_rec_set;
}

local function cast_v0_0_40_assoc_rec_set(t)
	return setmetatable(t, v0_0_40_assoc_rec_set_mt)
end

local function new_v0_0_40_assoc_rec_set(comment, defaultqos, grpjobs, grpjobsaccrue, grpsubmitjobs, grptres, grptresmins, grptresrunmins, grpwall, maxjobs, maxjobsaccrue, maxsubmitjobs, maxtresminsperjob, maxtresrunmins, maxtresperjob, maxtrespernode, maxwalldurationperjob, minpriothresh, parent, priority, qoslevel, fairshare)
	return cast_v0_0_40_assoc_rec_set({
		["comment"] = comment;
		["defaultqos"] = defaultqos;
		["grpjobs"] = grpjobs;
		["grpjobsaccrue"] = grpjobsaccrue;
		["grpsubmitjobs"] = grpsubmitjobs;
		["grptres"] = grptres;
		["grptresmins"] = grptresmins;
		["grptresrunmins"] = grptresrunmins;
		["grpwall"] = grpwall;
		["maxjobs"] = maxjobs;
		["maxjobsaccrue"] = maxjobsaccrue;
		["maxsubmitjobs"] = maxsubmitjobs;
		["maxtresminsperjob"] = maxtresminsperjob;
		["maxtresrunmins"] = maxtresrunmins;
		["maxtresperjob"] = maxtresperjob;
		["maxtrespernode"] = maxtrespernode;
		["maxwalldurationperjob"] = maxwalldurationperjob;
		["minpriothresh"] = minpriothresh;
		["parent"] = parent;
		["priority"] = priority;
		["qoslevel"] = qoslevel;
		["fairshare"] = fairshare;
	})
end

return {
	cast = cast_v0_0_40_assoc_rec_set;
	new = new_v0_0_40_assoc_rec_set;
}
