--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_partition_resp_partitions_inner class
local v0_0_41_openapi_partition_resp_partitions_inner = {}
local v0_0_41_openapi_partition_resp_partitions_inner_mt = {
	__name = "v0_0_41_openapi_partition_resp_partitions_inner";
	__index = v0_0_41_openapi_partition_resp_partitions_inner;
}

local function cast_v0_0_41_openapi_partition_resp_partitions_inner(t)
	return setmetatable(t, v0_0_41_openapi_partition_resp_partitions_inner_mt)
end

local function new_v0_0_41_openapi_partition_resp_partitions_inner(nodes, accounts, groups, qos, alternate, tres, cluster, select_type, cpus, defaults, grace_time, maximums, minimums, name, node_sets, priority, timeouts, partition, suspend_time)
	return cast_v0_0_41_openapi_partition_resp_partitions_inner({
		["nodes"] = nodes;
		["accounts"] = accounts;
		["groups"] = groups;
		["qos"] = qos;
		["alternate"] = alternate;
		["tres"] = tres;
		["cluster"] = cluster;
		["select_type"] = select_type;
		["cpus"] = cpus;
		["defaults"] = defaults;
		["grace_time"] = grace_time;
		["maximums"] = maximums;
		["minimums"] = minimums;
		["name"] = name;
		["node_sets"] = node_sets;
		["priority"] = priority;
		["timeouts"] = timeouts;
		["partition"] = partition;
		["suspend_time"] = suspend_time;
	})
end

return {
	cast = cast_v0_0_41_openapi_partition_resp_partitions_inner;
	new = new_v0_0_41_openapi_partition_resp_partitions_inner;
}
