--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_stats_msg class
local v0_0_39_stats_msg = {}
local v0_0_39_stats_msg_mt = {
	__name = "v0_0_39_stats_msg";
	__index = v0_0_39_stats_msg;
}

local function cast_v0_0_39_stats_msg(t)
	return setmetatable(t, v0_0_39_stats_msg_mt)
end

local function new_v0_0_39_stats_msg(parts_packed, req_time, req_time_start, server_thread_count, agent_queue_size, agent_count, agent_thread_count, dbd_agent_queue_size, gettimeofday_latency, schedule_cycle_max, schedule_cycle_last, schedule_cycle_total, schedule_cycle_mean, schedule_cycle_mean_depth, schedule_cycle_per_minute, schedule_queue_length, jobs_submitted, jobs_started, jobs_completed, jobs_canceled, jobs_failed, jobs_pending, jobs_running, job_states_ts, bf_backfilled_jobs, bf_last_backfilled_jobs, bf_backfilled_het_jobs, bf_cycle_counter, bf_cycle_mean, bf_depth_mean, bf_depth_mean_try, bf_cycle_sum, bf_cycle_last, bf_last_depth, bf_last_depth_try, bf_depth_sum, bf_depth_try_sum, bf_queue_len, bf_queue_len_mean, bf_queue_len_sum, bf_table_size, bf_table_size_mean, bf_when_last_cycle, bf_active, rpcs_by_message_type, rpcs_by_user)
	return cast_v0_0_39_stats_msg({
		["parts_packed"] = parts_packed;
		["req_time"] = req_time;
		["req_time_start"] = req_time_start;
		["server_thread_count"] = server_thread_count;
		["agent_queue_size"] = agent_queue_size;
		["agent_count"] = agent_count;
		["agent_thread_count"] = agent_thread_count;
		["dbd_agent_queue_size"] = dbd_agent_queue_size;
		["gettimeofday_latency"] = gettimeofday_latency;
		["schedule_cycle_max"] = schedule_cycle_max;
		["schedule_cycle_last"] = schedule_cycle_last;
		["schedule_cycle_total"] = schedule_cycle_total;
		["schedule_cycle_mean"] = schedule_cycle_mean;
		["schedule_cycle_mean_depth"] = schedule_cycle_mean_depth;
		["schedule_cycle_per_minute"] = schedule_cycle_per_minute;
		["schedule_queue_length"] = schedule_queue_length;
		["jobs_submitted"] = jobs_submitted;
		["jobs_started"] = jobs_started;
		["jobs_completed"] = jobs_completed;
		["jobs_canceled"] = jobs_canceled;
		["jobs_failed"] = jobs_failed;
		["jobs_pending"] = jobs_pending;
		["jobs_running"] = jobs_running;
		["job_states_ts"] = job_states_ts;
		["bf_backfilled_jobs"] = bf_backfilled_jobs;
		["bf_last_backfilled_jobs"] = bf_last_backfilled_jobs;
		["bf_backfilled_het_jobs"] = bf_backfilled_het_jobs;
		["bf_cycle_counter"] = bf_cycle_counter;
		["bf_cycle_mean"] = bf_cycle_mean;
		["bf_depth_mean"] = bf_depth_mean;
		["bf_depth_mean_try"] = bf_depth_mean_try;
		["bf_cycle_sum"] = bf_cycle_sum;
		["bf_cycle_last"] = bf_cycle_last;
		["bf_last_depth"] = bf_last_depth;
		["bf_last_depth_try"] = bf_last_depth_try;
		["bf_depth_sum"] = bf_depth_sum;
		["bf_depth_try_sum"] = bf_depth_try_sum;
		["bf_queue_len"] = bf_queue_len;
		["bf_queue_len_mean"] = bf_queue_len_mean;
		["bf_queue_len_sum"] = bf_queue_len_sum;
		["bf_table_size"] = bf_table_size;
		["bf_table_size_mean"] = bf_table_size_mean;
		["bf_when_last_cycle"] = bf_when_last_cycle;
		["bf_active"] = bf_active;
		["rpcs_by_message_type"] = rpcs_by_message_type;
		["rpcs_by_user"] = rpcs_by_user;
	})
end

return {
	cast = cast_v0_0_39_stats_msg;
	new = new_v0_0_39_stats_msg;
}
