--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_qos_limits_max_wall_clock_per class
local v0_0_40_qos_limits_max_wall_clock_per = {}
local v0_0_40_qos_limits_max_wall_clock_per_mt = {
	__name = "v0_0_40_qos_limits_max_wall_clock_per";
	__index = v0_0_40_qos_limits_max_wall_clock_per;
}

local function cast_v0_0_40_qos_limits_max_wall_clock_per(t)
	return setmetatable(t, v0_0_40_qos_limits_max_wall_clock_per_mt)
end

local function new_v0_0_40_qos_limits_max_wall_clock_per(qos, job)
	return cast_v0_0_40_qos_limits_max_wall_clock_per({
		["qos"] = qos;
		["job"] = job;
	})
end

return {
	cast = cast_v0_0_40_qos_limits_max_wall_clock_per;
	new = new_v0_0_40_qos_limits_max_wall_clock_per;
}
