--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_licenses_info class
local v0_0_39_licenses_info = {}
local v0_0_39_licenses_info_mt = {
	__name = "v0_0_39_licenses_info";
	__index = v0_0_39_licenses_info;
}

local function cast_v0_0_39_licenses_info(t)
	return setmetatable(t, v0_0_39_licenses_info_mt)
end

local function new_v0_0_39_licenses_info(meta, errors, warnings, licenses)
	return cast_v0_0_39_licenses_info({
		["meta"] = meta;
		["errors"] = errors;
		["warnings"] = warnings;
		["licenses"] = licenses;
	})
end

return {
	cast = cast_v0_0_39_licenses_info;
	new = new_v0_0_39_licenses_info;
}
