--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_partition_info_maximums_oversubscribe class
local v0_0_40_partition_info_maximums_oversubscribe = {}
local v0_0_40_partition_info_maximums_oversubscribe_mt = {
	__name = "v0_0_40_partition_info_maximums_oversubscribe";
	__index = v0_0_40_partition_info_maximums_oversubscribe;
}

local function cast_v0_0_40_partition_info_maximums_oversubscribe(t)
	return setmetatable(t, v0_0_40_partition_info_maximums_oversubscribe_mt)
end

local function new_v0_0_40_partition_info_maximums_oversubscribe(jobs, flags)
	return cast_v0_0_40_partition_info_maximums_oversubscribe({
		["jobs"] = jobs;
		["flags"] = flags;
	})
end

return {
	cast = cast_v0_0_40_partition_info_maximums_oversubscribe;
	new = new_v0_0_40_partition_info_maximums_oversubscribe;
}
