--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_partition_info_nodes class
local v0_0_39_partition_info_nodes = {}
local v0_0_39_partition_info_nodes_mt = {
	__name = "v0_0_39_partition_info_nodes";
	__index = v0_0_39_partition_info_nodes;
}

local function cast_v0_0_39_partition_info_nodes(t)
	return setmetatable(t, v0_0_39_partition_info_nodes_mt)
end

local function new_v0_0_39_partition_info_nodes(allowed_allocation, configured, total)
	return cast_v0_0_39_partition_info_nodes({
		["allowed_allocation"] = allowed_allocation;
		["configured"] = configured;
		["total"] = total;
	})
end

return {
	cast = cast_v0_0_39_partition_info_nodes;
	new = new_v0_0_39_partition_info_nodes;
}
