--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job_info class
local v0_0_39_job_info = {}
local v0_0_39_job_info_mt = {
	__name = "v0_0_39_job_info";
	__index = v0_0_39_job_info;
}

local function cast_v0_0_39_job_info(t)
	return setmetatable(t, v0_0_39_job_info_mt)
end

local function new_v0_0_39_job_info(account, accrue_time, admin_comment, allocating_node, array_job_id, array_task_id, array_max_tasks, array_task_string, association_id, batch_features, batch_flag, batch_host, flags, burst_buffer, burst_buffer_state, cluster, cluster_features, command, comment, container, container_id, contiguous, core_spec, thread_spec, cores_per_socket, billable_tres, cpus_per_task, cpu_frequency_minimum, cpu_frequency_maximum, cpu_frequency_governor, cpus_per_tres, cron, deadline, delay_boot, dependency, derived_exit_code, eligible_time, end_time, excluded_nodes, exit_code, extra, failed_node, features, federation_origin, federation_siblings_active, federation_siblings_viable, gres_detail, group_id, group_name, het_job_id, het_job_id_set, het_job_offset, job_id, job_resources, job_size_str, job_state, last_sched_evaluation, licenses, mail_type, mail_user, max_cpus, max_nodes, mcs_label, memory_per_tres, name, network, nodes, nice, tasks_per_core, tasks_per_tres, tasks_per_node, tasks_per_socket, tasks_per_board, cpus, node_count, tasks, partition, prefer, memory_per_cpu, memory_per_node, minimum_cpus_per_node, minimum_tmp_disk_per_node, power, preempt_time, preemptable_time, pre_sus_time, hold, priority, profile, qos, reboot, required_nodes, minimum_switches, requeue, resize_time, restart_cnt, resv_name, scheduled_nodes, selinux_context, shared, exclusive, oversubscribe, show_flags, sockets_per_board, sockets_per_node, start_time, state_description, state_reason, standard_error, standard_input, standard_output, submit_time, suspend_time, system_comment, time_limit, time_minimum, threads_per_core, tres_bind, tres_freq, tres_per_job, tres_per_node, tres_per_socket, tres_per_task, tres_req_str, tres_alloc_str, user_id, user_name, maximum_switch_wait_time, wckey, current_working_directory)
	return cast_v0_0_39_job_info({
		["account"] = account;
		["accrue_time"] = accrue_time;
		["admin_comment"] = admin_comment;
		["allocating_node"] = allocating_node;
		["array_job_id"] = array_job_id;
		["array_task_id"] = array_task_id;
		["array_max_tasks"] = array_max_tasks;
		["array_task_string"] = array_task_string;
		["association_id"] = association_id;
		["batch_features"] = batch_features;
		["batch_flag"] = batch_flag;
		["batch_host"] = batch_host;
		["flags"] = flags;
		["burst_buffer"] = burst_buffer;
		["burst_buffer_state"] = burst_buffer_state;
		["cluster"] = cluster;
		["cluster_features"] = cluster_features;
		["command"] = command;
		["comment"] = comment;
		["container"] = container;
		["container_id"] = container_id;
		["contiguous"] = contiguous;
		["core_spec"] = core_spec;
		["thread_spec"] = thread_spec;
		["cores_per_socket"] = cores_per_socket;
		["billable_tres"] = billable_tres;
		["cpus_per_task"] = cpus_per_task;
		["cpu_frequency_minimum"] = cpu_frequency_minimum;
		["cpu_frequency_maximum"] = cpu_frequency_maximum;
		["cpu_frequency_governor"] = cpu_frequency_governor;
		["cpus_per_tres"] = cpus_per_tres;
		["cron"] = cron;
		["deadline"] = deadline;
		["delay_boot"] = delay_boot;
		["dependency"] = dependency;
		["derived_exit_code"] = derived_exit_code;
		["eligible_time"] = eligible_time;
		["end_time"] = end_time;
		["excluded_nodes"] = excluded_nodes;
		["exit_code"] = exit_code;
		["extra"] = extra;
		["failed_node"] = failed_node;
		["features"] = features;
		["federation_origin"] = federation_origin;
		["federation_siblings_active"] = federation_siblings_active;
		["federation_siblings_viable"] = federation_siblings_viable;
		["gres_detail"] = gres_detail;
		["group_id"] = group_id;
		["group_name"] = group_name;
		["het_job_id"] = het_job_id;
		["het_job_id_set"] = het_job_id_set;
		["het_job_offset"] = het_job_offset;
		["job_id"] = job_id;
		["job_resources"] = job_resources;
		["job_size_str"] = job_size_str;
		["job_state"] = job_state;
		["last_sched_evaluation"] = last_sched_evaluation;
		["licenses"] = licenses;
		["mail_type"] = mail_type;
		["mail_user"] = mail_user;
		["max_cpus"] = max_cpus;
		["max_nodes"] = max_nodes;
		["mcs_label"] = mcs_label;
		["memory_per_tres"] = memory_per_tres;
		["name"] = name;
		["network"] = network;
		["nodes"] = nodes;
		["nice"] = nice;
		["tasks_per_core"] = tasks_per_core;
		["tasks_per_tres"] = tasks_per_tres;
		["tasks_per_node"] = tasks_per_node;
		["tasks_per_socket"] = tasks_per_socket;
		["tasks_per_board"] = tasks_per_board;
		["cpus"] = cpus;
		["node_count"] = node_count;
		["tasks"] = tasks;
		["partition"] = partition;
		["prefer"] = prefer;
		["memory_per_cpu"] = memory_per_cpu;
		["memory_per_node"] = memory_per_node;
		["minimum_cpus_per_node"] = minimum_cpus_per_node;
		["minimum_tmp_disk_per_node"] = minimum_tmp_disk_per_node;
		["power"] = power;
		["preempt_time"] = preempt_time;
		["preemptable_time"] = preemptable_time;
		["pre_sus_time"] = pre_sus_time;
		["hold"] = hold;
		["priority"] = priority;
		["profile"] = profile;
		["qos"] = qos;
		["reboot"] = reboot;
		["required_nodes"] = required_nodes;
		["minimum_switches"] = minimum_switches;
		["requeue"] = requeue;
		["resize_time"] = resize_time;
		["restart_cnt"] = restart_cnt;
		["resv_name"] = resv_name;
		["scheduled_nodes"] = scheduled_nodes;
		["selinux_context"] = selinux_context;
		["shared"] = shared;
		["exclusive"] = exclusive;
		["oversubscribe"] = oversubscribe;
		["show_flags"] = show_flags;
		["sockets_per_board"] = sockets_per_board;
		["sockets_per_node"] = sockets_per_node;
		["start_time"] = start_time;
		["state_description"] = state_description;
		["state_reason"] = state_reason;
		["standard_error"] = standard_error;
		["standard_input"] = standard_input;
		["standard_output"] = standard_output;
		["submit_time"] = submit_time;
		["suspend_time"] = suspend_time;
		["system_comment"] = system_comment;
		["time_limit"] = time_limit;
		["time_minimum"] = time_minimum;
		["threads_per_core"] = threads_per_core;
		["tres_bind"] = tres_bind;
		["tres_freq"] = tres_freq;
		["tres_per_job"] = tres_per_job;
		["tres_per_node"] = tres_per_node;
		["tres_per_socket"] = tres_per_socket;
		["tres_per_task"] = tres_per_task;
		["tres_req_str"] = tres_req_str;
		["tres_alloc_str"] = tres_alloc_str;
		["user_id"] = user_id;
		["user_name"] = user_name;
		["maximum_switch_wait_time"] = maximum_switch_wait_time;
		["wckey"] = wckey;
		["current_working_directory"] = current_working_directory;
	})
end

return {
	cast = cast_v0_0_39_job_info;
	new = new_v0_0_39_job_info;
}
