--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_cron_entry_line class
local v0_0_39_cron_entry_line = {}
local v0_0_39_cron_entry_line_mt = {
	__name = "v0_0_39_cron_entry_line";
	__index = v0_0_39_cron_entry_line;
}

local function cast_v0_0_39_cron_entry_line(t)
	return setmetatable(t, v0_0_39_cron_entry_line_mt)
end

local function new_v0_0_39_cron_entry_line(start, End_)
	return cast_v0_0_39_cron_entry_line({
		["start"] = start;
		["end"] = End_;
	})
end

return {
	cast = cast_v0_0_39_cron_entry_line;
	new = new_v0_0_39_cron_entry_line;
}
