--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory class
local v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory = {}
local v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory_mt = {
	__name = "v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory";
	__index = v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory;
}

local function cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(t)
	return setmetatable(t, v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory_mt)
end

local function new_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory(used, allocated)
	return cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory({
		["used"] = used;
		["allocated"] = allocated;
	})
end

return {
	cast = cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory;
	new = new_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_allocation_inner_memory;
}
