--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_partition_info_qos class
local v0_0_40_partition_info_qos = {}
local v0_0_40_partition_info_qos_mt = {
	__name = "v0_0_40_partition_info_qos";
	__index = v0_0_40_partition_info_qos;
}

local function cast_v0_0_40_partition_info_qos(t)
	return setmetatable(t, v0_0_40_partition_info_qos_mt)
end

local function new_v0_0_40_partition_info_qos(allowed, deny, assigned)
	return cast_v0_0_40_partition_info_qos({
		["allowed"] = allowed;
		["deny"] = deny;
		["assigned"] = assigned;
	})
end

return {
	cast = cast_v0_0_40_partition_info_qos;
	new = new_v0_0_40_partition_info_qos;
}
