--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_warning class
local v0_0_39_warning = {}
local v0_0_39_warning_mt = {
	__name = "v0_0_39_warning";
	__index = v0_0_39_warning;
}

local function cast_v0_0_39_warning(t)
	return setmetatable(t, v0_0_39_warning_mt)
end

local function new_v0_0_39_warning(warning, source, description)
	return cast_v0_0_39_warning({
		["warning"] = warning;
		["source"] = source;
		["description"] = description;
	})
end

return {
	cast = cast_v0_0_39_warning;
	new = new_v0_0_39_warning;
}
