--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_assoc_shares_obj_wrap_fairshare class
local v0_0_40_assoc_shares_obj_wrap_fairshare = {}
local v0_0_40_assoc_shares_obj_wrap_fairshare_mt = {
	__name = "v0_0_40_assoc_shares_obj_wrap_fairshare";
	__index = v0_0_40_assoc_shares_obj_wrap_fairshare;
}

local function cast_v0_0_40_assoc_shares_obj_wrap_fairshare(t)
	return setmetatable(t, v0_0_40_assoc_shares_obj_wrap_fairshare_mt)
end

local function new_v0_0_40_assoc_shares_obj_wrap_fairshare(factor, level)
	return cast_v0_0_40_assoc_shares_obj_wrap_fairshare({
		["factor"] = factor;
		["level"] = level;
	})
end

return {
	cast = cast_v0_0_40_assoc_shares_obj_wrap_fairshare;
	new = new_v0_0_40_assoc_shares_obj_wrap_fairshare;
}
