--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_job_submit_req class
local v0_0_40_job_submit_req = {}
local v0_0_40_job_submit_req_mt = {
	__name = "v0_0_40_job_submit_req";
	__index = v0_0_40_job_submit_req;
}

local function cast_v0_0_40_job_submit_req(t)
	return setmetatable(t, v0_0_40_job_submit_req_mt)
end

local function new_v0_0_40_job_submit_req(script, jobs, job)
	return cast_v0_0_40_job_submit_req({
		["script"] = script;
		["jobs"] = jobs;
		["job"] = job;
	})
end

return {
	cast = cast_v0_0_40_job_submit_req;
	new = new_v0_0_40_job_submit_req;
}
