--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_assoc_shares_obj_wrap class
local v0_0_40_assoc_shares_obj_wrap = {}
local v0_0_40_assoc_shares_obj_wrap_mt = {
	__name = "v0_0_40_assoc_shares_obj_wrap";
	__index = v0_0_40_assoc_shares_obj_wrap;
}

local function cast_v0_0_40_assoc_shares_obj_wrap(t)
	return setmetatable(t, v0_0_40_assoc_shares_obj_wrap_mt)
end

local function new_v0_0_40_assoc_shares_obj_wrap(id, cluster, name, parent, partition, shares_normalized, shares, tres, effective_usage, usage_normalized, usage, fairshare, type)
	return cast_v0_0_40_assoc_shares_obj_wrap({
		["id"] = id;
		["cluster"] = cluster;
		["name"] = name;
		["parent"] = parent;
		["partition"] = partition;
		["shares_normalized"] = shares_normalized;
		["shares"] = shares;
		["tres"] = tres;
		["effective_usage"] = effective_usage;
		["usage_normalized"] = usage_normalized;
		["usage"] = usage;
		["fairshare"] = fairshare;
		["type"] = type;
	})
end

return {
	cast = cast_v0_0_40_assoc_shares_obj_wrap;
	new = new_v0_0_40_assoc_shares_obj_wrap;
}
