--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_kill_jobs_msg class
local v0_0_40_kill_jobs_msg = {}
local v0_0_40_kill_jobs_msg_mt = {
	__name = "v0_0_40_kill_jobs_msg";
	__index = v0_0_40_kill_jobs_msg;
}

local function cast_v0_0_40_kill_jobs_msg(t)
	return setmetatable(t, v0_0_40_kill_jobs_msg_mt)
end

local function new_v0_0_40_kill_jobs_msg(account, flags, job_name, jobs, partition, qos, reservation, signal, job_state, user_id, user_name, wckey, nodes)
	return cast_v0_0_40_kill_jobs_msg({
		["account"] = account;
		["flags"] = flags;
		["job_name"] = job_name;
		["jobs"] = jobs;
		["partition"] = partition;
		["qos"] = qos;
		["reservation"] = reservation;
		["signal"] = signal;
		["job_state"] = job_state;
		["user_id"] = user_id;
		["user_name"] = user_name;
		["wckey"] = wckey;
		["nodes"] = nodes;
	})
end

return {
	cast = cast_v0_0_40_kill_jobs_msg;
	new = new_v0_0_40_kill_jobs_msg;
}
