--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_jobs_response class
local v0_0_39_jobs_response = {}
local v0_0_39_jobs_response_mt = {
	__name = "v0_0_39_jobs_response";
	__index = v0_0_39_jobs_response;
}

local function cast_v0_0_39_jobs_response(t)
	return setmetatable(t, v0_0_39_jobs_response_mt)
end

local function new_v0_0_39_jobs_response(meta, errors, warnings, jobs)
	return cast_v0_0_39_jobs_response({
		["meta"] = meta;
		["errors"] = errors;
		["warnings"] = warnings;
		["jobs"] = jobs;
	})
end

return {
	cast = cast_v0_0_39_jobs_response;
	new = new_v0_0_39_jobs_response;
}
