--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_reservation_resp_reservations_inner class
local v0_0_41_openapi_reservation_resp_reservations_inner = {}
local v0_0_41_openapi_reservation_resp_reservations_inner_mt = {
	__name = "v0_0_41_openapi_reservation_resp_reservations_inner";
	__index = v0_0_41_openapi_reservation_resp_reservations_inner;
}

local function cast_v0_0_41_openapi_reservation_resp_reservations_inner(t)
	return setmetatable(t, v0_0_41_openapi_reservation_resp_reservations_inner_mt)
end

local function new_v0_0_41_openapi_reservation_resp_reservations_inner(accounts, burst_buffer, core_count, core_specializations, end_time, features, flags, groups, licenses, max_start_delay, name, node_count, node_list, partition, purge_completed, start_time, watts, tres, users)
	return cast_v0_0_41_openapi_reservation_resp_reservations_inner({
		["accounts"] = accounts;
		["burst_buffer"] = burst_buffer;
		["core_count"] = core_count;
		["core_specializations"] = core_specializations;
		["end_time"] = end_time;
		["features"] = features;
		["flags"] = flags;
		["groups"] = groups;
		["licenses"] = licenses;
		["max_start_delay"] = max_start_delay;
		["name"] = name;
		["node_count"] = node_count;
		["node_list"] = node_list;
		["partition"] = partition;
		["purge_completed"] = purge_completed;
		["start_time"] = start_time;
		["watts"] = watts;
		["tres"] = tres;
		["users"] = users;
	})
end

return {
	cast = cast_v0_0_41_openapi_reservation_resp_reservations_inner;
	new = new_v0_0_41_openapi_reservation_resp_reservations_inner;
}
