--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_shares_resp_warnings_inner class
local v0_0_41_openapi_shares_resp_warnings_inner = {}
local v0_0_41_openapi_shares_resp_warnings_inner_mt = {
	__name = "v0_0_41_openapi_shares_resp_warnings_inner";
	__index = v0_0_41_openapi_shares_resp_warnings_inner;
}

local function cast_v0_0_41_openapi_shares_resp_warnings_inner(t)
	return setmetatable(t, v0_0_41_openapi_shares_resp_warnings_inner_mt)
end

local function new_v0_0_41_openapi_shares_resp_warnings_inner(description, source)
	return cast_v0_0_41_openapi_shares_resp_warnings_inner({
		["description"] = description;
		["source"] = source;
	})
end

return {
	cast = cast_v0_0_41_openapi_shares_resp_warnings_inner;
	new = new_v0_0_41_openapi_shares_resp_warnings_inner;
}
