--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_config_resp_clusters_inner class
local v0_0_41_openapi_slurmdbd_config_resp_clusters_inner = {}
local v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_mt = {
	__name = "v0_0_41_openapi_slurmdbd_config_resp_clusters_inner";
	__index = v0_0_41_openapi_slurmdbd_config_resp_clusters_inner;
}

local function cast_v0_0_41_openapi_slurmdbd_config_resp_clusters_inner(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_mt)
end

local function new_v0_0_41_openapi_slurmdbd_config_resp_clusters_inner(controller, flags, name, nodes, select_plugin, associations, rpc_version, tres)
	return cast_v0_0_41_openapi_slurmdbd_config_resp_clusters_inner({
		["controller"] = controller;
		["flags"] = flags;
		["name"] = name;
		["nodes"] = nodes;
		["select_plugin"] = select_plugin;
		["associations"] = associations;
		["rpc_version"] = rpc_version;
		["tres"] = tres;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_config_resp_clusters_inner;
	new = new_v0_0_41_openapi_slurmdbd_config_resp_clusters_inner;
}
