--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job_submission class
local v0_0_39_job_submission = {}
local v0_0_39_job_submission_mt = {
	__name = "v0_0_39_job_submission";
	__index = v0_0_39_job_submission;
}

local function cast_v0_0_39_job_submission(t)
	return setmetatable(t, v0_0_39_job_submission_mt)
end

local function new_v0_0_39_job_submission(script, job, jobs)
	return cast_v0_0_39_job_submission({
		["script"] = script;
		["job"] = job;
		["jobs"] = jobs;
	})
end

return {
	cast = cast_v0_0_39_job_submission;
	new = new_v0_0_39_job_submission;
}
