--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group class
local v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group = {}
local v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group_mt = {
	__name = "v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group";
	__index = v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group;
}

local function cast_v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group_mt)
end

local function new_v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group(minutes, active)
	return cast_v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group({
		["minutes"] = minutes;
		["active"] = active;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group;
	new = new_v0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_tres_group;
}
