--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs class
local v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs = {}
local v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs_mt = {
	__name = "v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs";
	__index = v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs;
}

local function cast_v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs(t)
	return setmetatable(t, v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs_mt)
end

local function new_v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs(set, infinite, Number_)
	return cast_v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs;
	new = new_v0_0_41_openapi_users_add_cond_resp_association_condition_association_grpsubmitjobs;
}
