--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_job_desc_msg_rlimits_core class
local v0_0_41_job_desc_msg_rlimits_core = {}
local v0_0_41_job_desc_msg_rlimits_core_mt = {
	__name = "v0_0_41_job_desc_msg_rlimits_core";
	__index = v0_0_41_job_desc_msg_rlimits_core;
}

local function cast_v0_0_41_job_desc_msg_rlimits_core(t)
	return setmetatable(t, v0_0_41_job_desc_msg_rlimits_core_mt)
end

local function new_v0_0_41_job_desc_msg_rlimits_core(set, infinite, Number_)
	return cast_v0_0_41_job_desc_msg_rlimits_core({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_job_desc_msg_rlimits_core;
	new = new_v0_0_41_job_desc_msg_rlimits_core;
}
