--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_openapi_meta_slurm_version class
local v0_0_40_openapi_meta_slurm_version = {}
local v0_0_40_openapi_meta_slurm_version_mt = {
	__name = "v0_0_40_openapi_meta_slurm_version";
	__index = v0_0_40_openapi_meta_slurm_version;
}

local function cast_v0_0_40_openapi_meta_slurm_version(t)
	return setmetatable(t, v0_0_40_openapi_meta_slurm_version_mt)
end

local function new_v0_0_40_openapi_meta_slurm_version(major, micro, minor)
	return cast_v0_0_40_openapi_meta_slurm_version({
		["major"] = major;
		["micro"] = micro;
		["minor"] = minor;
	})
end

return {
	cast = cast_v0_0_40_openapi_meta_slurm_version;
	new = new_v0_0_40_openapi_meta_slurm_version;
}
