--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups class
local v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups = {}
local v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_mt = {
	__name = "v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups";
	__index = v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups;
}

local function cast_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_mt)
end

local function new_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups(hourly, daily, monthly)
	return cast_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups({
		["hourly"] = hourly;
		["daily"] = daily;
		["monthly"] = monthly;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups;
	new = new_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups;
}
