--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_assoc_short class
local v0_0_39_assoc_short = {}
local v0_0_39_assoc_short_mt = {
	__name = "v0_0_39_assoc_short";
	__index = v0_0_39_assoc_short;
}

local function cast_v0_0_39_assoc_short(t)
	return setmetatable(t, v0_0_39_assoc_short_mt)
end

local function new_v0_0_39_assoc_short(account, cluster, partition, user)
	return cast_v0_0_39_assoc_short({
		["account"] = account;
		["cluster"] = cluster;
		["partition"] = partition;
		["user"] = user;
	})
end

return {
	cast = cast_v0_0_39_assoc_short;
	new = new_v0_0_39_assoc_short;
}
