--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_openapi_accounts_add_cond_resp_str class
local v0_0_40_openapi_accounts_add_cond_resp_str = {}
local v0_0_40_openapi_accounts_add_cond_resp_str_mt = {
	__name = "v0_0_40_openapi_accounts_add_cond_resp_str";
	__index = v0_0_40_openapi_accounts_add_cond_resp_str;
}

local function cast_v0_0_40_openapi_accounts_add_cond_resp_str(t)
	return setmetatable(t, v0_0_40_openapi_accounts_add_cond_resp_str_mt)
end

local function new_v0_0_40_openapi_accounts_add_cond_resp_str(added_accounts, meta, errors, warnings)
	return cast_v0_0_40_openapi_accounts_add_cond_resp_str({
		["added_accounts"] = added_accounts;
		["meta"] = meta;
		["errors"] = errors;
		["warnings"] = warnings;
	})
end

return {
	cast = cast_v0_0_40_openapi_accounts_add_cond_resp_str;
	new = new_v0_0_40_openapi_accounts_add_cond_resp_str;
}
