--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_user_default class
local v0_0_39_user_default = {}
local v0_0_39_user_default_mt = {
	__name = "v0_0_39_user_default";
	__index = v0_0_39_user_default;
}

local function cast_v0_0_39_user_default(t)
	return setmetatable(t, v0_0_39_user_default_mt)
end

local function new_v0_0_39_user_default(account, wckey)
	return cast_v0_0_39_user_default({
		["account"] = account;
		["wckey"] = wckey;
	})
end

return {
	cast = cast_v0_0_39_user_default;
	new = new_v0_0_39_user_default;
}
