--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_partition_info_cpus class
local v0_0_40_partition_info_cpus = {}
local v0_0_40_partition_info_cpus_mt = {
	__name = "v0_0_40_partition_info_cpus";
	__index = v0_0_40_partition_info_cpus;
}

local function cast_v0_0_40_partition_info_cpus(t)
	return setmetatable(t, v0_0_40_partition_info_cpus_mt)
end

local function new_v0_0_40_partition_info_cpus(task_binding, total)
	return cast_v0_0_40_partition_info_cpus({
		["task_binding"] = task_binding;
		["total"] = total;
	})
end

return {
	cast = cast_v0_0_40_partition_info_cpus;
	new = new_v0_0_40_partition_info_cpus;
}
