--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_kill_jobs_resp_job_error class
local v0_0_40_kill_jobs_resp_job_error = {}
local v0_0_40_kill_jobs_resp_job_error_mt = {
	__name = "v0_0_40_kill_jobs_resp_job_error";
	__index = v0_0_40_kill_jobs_resp_job_error;
}

local function cast_v0_0_40_kill_jobs_resp_job_error(t)
	return setmetatable(t, v0_0_40_kill_jobs_resp_job_error_mt)
end

local function new_v0_0_40_kill_jobs_resp_job_error(String_, code, message)
	return cast_v0_0_40_kill_jobs_resp_job_error({
		["string"] = String_;
		["code"] = code;
		["message"] = message;
	})
end

return {
	cast = cast_v0_0_40_kill_jobs_resp_job_error;
	new = new_v0_0_40_kill_jobs_resp_job_error;
}
