--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_openapi_error class
local v0_0_40_openapi_error = {}
local v0_0_40_openapi_error_mt = {
	__name = "v0_0_40_openapi_error";
	__index = v0_0_40_openapi_error;
}

local function cast_v0_0_40_openapi_error(t)
	return setmetatable(t, v0_0_40_openapi_error_mt)
end

local function new_v0_0_40_openapi_error(description, error_number, error, source)
	return cast_v0_0_40_openapi_error({
		["description"] = description;
		["error_number"] = error_number;
		["error"] = error;
		["source"] = source;
	})
end

return {
	cast = cast_v0_0_40_openapi_error;
	new = new_v0_0_40_openapi_error;
}
