--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_coord class
local v0_0_39_coord = {}
local v0_0_39_coord_mt = {
	__name = "v0_0_39_coord";
	__index = v0_0_39_coord;
}

local function cast_v0_0_39_coord(t)
	return setmetatable(t, v0_0_39_coord_mt)
end

local function new_v0_0_39_coord(name, direct)
	return cast_v0_0_39_coord({
		["name"] = name;
		["direct"] = direct;
	})
end

return {
	cast = cast_v0_0_39_coord;
	new = new_v0_0_39_coord;
}
