--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_nodes_resp_nodes_inner_last_busy class
local v0_0_41_openapi_nodes_resp_nodes_inner_last_busy = {}
local v0_0_41_openapi_nodes_resp_nodes_inner_last_busy_mt = {
	__name = "v0_0_41_openapi_nodes_resp_nodes_inner_last_busy";
	__index = v0_0_41_openapi_nodes_resp_nodes_inner_last_busy;
}

local function cast_v0_0_41_openapi_nodes_resp_nodes_inner_last_busy(t)
	return setmetatable(t, v0_0_41_openapi_nodes_resp_nodes_inner_last_busy_mt)
end

local function new_v0_0_41_openapi_nodes_resp_nodes_inner_last_busy(set, infinite, Number_)
	return cast_v0_0_41_openapi_nodes_resp_nodes_inner_last_busy({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_openapi_nodes_resp_nodes_inner_last_busy;
	new = new_v0_0_41_openapi_nodes_resp_nodes_inner_last_busy;
}
