--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes class
local v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes = {}
local v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_mt = {
	__name = "v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes";
	__index = v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes;
}

local function cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(t)
	return setmetatable(t, v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes_mt)
end

local function new_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes(count, select_type, list, whole, allocation)
	return cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes({
		["count"] = count;
		["select_type"] = select_type;
		["list"] = list;
		["whole"] = whole;
		["allocation"] = allocation;
	})
end

return {
	cast = cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes;
	new = new_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_nodes;
}
