--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_shares_resp_msg class
local v0_0_40_shares_resp_msg = {}
local v0_0_40_shares_resp_msg_mt = {
	__name = "v0_0_40_shares_resp_msg";
	__index = v0_0_40_shares_resp_msg;
}

local function cast_v0_0_40_shares_resp_msg(t)
	return setmetatable(t, v0_0_40_shares_resp_msg_mt)
end

local function new_v0_0_40_shares_resp_msg(shares, total_shares)
	return cast_v0_0_40_shares_resp_msg({
		["shares"] = shares;
		["total_shares"] = total_shares;
	})
end

return {
	cast = cast_v0_0_40_shares_resp_msg;
	new = new_v0_0_40_shares_resp_msg;
}
