--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_job_info_resp_jobs_inner_job_resources class
local v0_0_41_openapi_job_info_resp_jobs_inner_job_resources = {}
local v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_mt = {
	__name = "v0_0_41_openapi_job_info_resp_jobs_inner_job_resources";
	__index = v0_0_41_openapi_job_info_resp_jobs_inner_job_resources;
}

local function cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(t)
	return setmetatable(t, v0_0_41_openapi_job_info_resp_jobs_inner_job_resources_mt)
end

local function new_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources(select_type, nodes, cpus, threads_per_core)
	return cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources({
		["select_type"] = select_type;
		["nodes"] = nodes;
		["cpus"] = cpus;
		["threads_per_core"] = threads_per_core;
	})
end

return {
	cast = cast_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources;
	new = new_v0_0_41_openapi_job_info_resp_jobs_inner_job_resources;
}
