--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_shares_resp_shares_shares_inner_shares class
local v0_0_41_openapi_shares_resp_shares_shares_inner_shares = {}
local v0_0_41_openapi_shares_resp_shares_shares_inner_shares_mt = {
	__name = "v0_0_41_openapi_shares_resp_shares_shares_inner_shares";
	__index = v0_0_41_openapi_shares_resp_shares_shares_inner_shares;
}

local function cast_v0_0_41_openapi_shares_resp_shares_shares_inner_shares(t)
	return setmetatable(t, v0_0_41_openapi_shares_resp_shares_shares_inner_shares_mt)
end

local function new_v0_0_41_openapi_shares_resp_shares_shares_inner_shares(set, infinite, Number_)
	return cast_v0_0_41_openapi_shares_resp_shares_shares_inner_shares({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_openapi_shares_resp_shares_shares_inner_shares;
	new = new_v0_0_41_openapi_shares_resp_shares_shares_inner_shares;
}
