--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_accounting_allocated class
local v0_0_39_accounting_allocated = {}
local v0_0_39_accounting_allocated_mt = {
	__name = "v0_0_39_accounting_allocated";
	__index = v0_0_39_accounting_allocated;
}

local function cast_v0_0_39_accounting_allocated(t)
	return setmetatable(t, v0_0_39_accounting_allocated_mt)
end

local function new_v0_0_39_accounting_allocated(seconds)
	return cast_v0_0_39_accounting_allocated({
		["seconds"] = seconds;
	})
end

return {
	cast = cast_v0_0_39_accounting_allocated;
	new = new_v0_0_39_accounting_allocated;
}
