--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes class
local v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes = {}
local v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes_mt = {
	__name = "v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes";
	__index = v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes;
}

local function cast_v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes(t)
	return setmetatable(t, v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes_mt)
end

local function new_v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes(set, infinite, Number_)
	return cast_v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes;
	new = new_v0_0_41_openapi_partition_resp_partitions_inner_maximums_nodes;
}
