--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner class
local v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner = {}
local v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner_mt = {
	__name = "v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner";
	__index = v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner;
}

local function cast_v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner(t)
	return setmetatable(t, v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner_mt)
end

local function new_v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner(node, core)
	return cast_v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner({
		["node"] = node;
		["core"] = core;
	})
end

return {
	cast = cast_v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner;
	new = new_v0_0_41_openapi_reservation_resp_reservations_inner_core_specializations_inner;
}
