--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job_info_power class
local v0_0_39_job_info_power = {}
local v0_0_39_job_info_power_mt = {
	__name = "v0_0_39_job_info_power";
	__index = v0_0_39_job_info_power;
}

local function cast_v0_0_39_job_info_power(t)
	return setmetatable(t, v0_0_39_job_info_power_mt)
end

local function new_v0_0_39_job_info_power(flags)
	return cast_v0_0_39_job_info_power({
		["flags"] = flags;
	})
end

return {
	cast = cast_v0_0_39_job_info_power;
	new = new_v0_0_39_job_info_power;
}
