--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_cluster_rec_controller class
local v0_0_40_cluster_rec_controller = {}
local v0_0_40_cluster_rec_controller_mt = {
	__name = "v0_0_40_cluster_rec_controller";
	__index = v0_0_40_cluster_rec_controller;
}

local function cast_v0_0_40_cluster_rec_controller(t)
	return setmetatable(t, v0_0_40_cluster_rec_controller_mt)
end

local function new_v0_0_40_cluster_rec_controller(host, port)
	return cast_v0_0_40_cluster_rec_controller({
		["host"] = host;
		["port"] = port;
	})
end

return {
	cast = cast_v0_0_40_cluster_rec_controller;
	new = new_v0_0_40_cluster_rec_controller;
}
