--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_diag_resp_statistics_schedule_exit class
local v0_0_41_openapi_diag_resp_statistics_schedule_exit = {}
local v0_0_41_openapi_diag_resp_statistics_schedule_exit_mt = {
	__name = "v0_0_41_openapi_diag_resp_statistics_schedule_exit";
	__index = v0_0_41_openapi_diag_resp_statistics_schedule_exit;
}

local function cast_v0_0_41_openapi_diag_resp_statistics_schedule_exit(t)
	return setmetatable(t, v0_0_41_openapi_diag_resp_statistics_schedule_exit_mt)
end

local function new_v0_0_41_openapi_diag_resp_statistics_schedule_exit(end_job_queue, default_queue_depth, max_job_start, max_rpc_cnt, max_sched_time, licenses)
	return cast_v0_0_41_openapi_diag_resp_statistics_schedule_exit({
		["end_job_queue"] = end_job_queue;
		["default_queue_depth"] = default_queue_depth;
		["max_job_start"] = max_job_start;
		["max_rpc_cnt"] = max_rpc_cnt;
		["max_sched_time"] = max_sched_time;
		["licenses"] = licenses;
	})
end

return {
	cast = cast_v0_0_41_openapi_diag_resp_statistics_schedule_exit;
	new = new_v0_0_41_openapi_diag_resp_statistics_schedule_exit;
}
