--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_user_short class
local v0_0_40_user_short = {}
local v0_0_40_user_short_mt = {
	__name = "v0_0_40_user_short";
	__index = v0_0_40_user_short;
}

local function cast_v0_0_40_user_short(t)
	return setmetatable(t, v0_0_40_user_short_mt)
end

local function new_v0_0_40_user_short(adminlevel, defaultaccount, defaultwckey)
	return cast_v0_0_40_user_short({
		["adminlevel"] = adminlevel;
		["defaultaccount"] = defaultaccount;
		["defaultwckey"] = defaultwckey;
	})
end

return {
	cast = cast_v0_0_40_user_short;
	new = new_v0_0_40_user_short;
}
