--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_accounting class
local v0_0_40_accounting = {}
local v0_0_40_accounting_mt = {
	__name = "v0_0_40_accounting";
	__index = v0_0_40_accounting;
}

local function cast_v0_0_40_accounting(t)
	return setmetatable(t, v0_0_40_accounting_mt)
end

local function new_v0_0_40_accounting(allocated, id, start, TRES)
	return cast_v0_0_40_accounting({
		["allocated"] = allocated;
		["id"] = id;
		["start"] = start;
		["TRES"] = TRES;
	})
end

return {
	cast = cast_v0_0_40_accounting;
	new = new_v0_0_40_accounting;
}
