--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_pings class
local v0_0_39_pings = {}
local v0_0_39_pings_mt = {
	__name = "v0_0_39_pings";
	__index = v0_0_39_pings;
}

local function cast_v0_0_39_pings(t)
	return setmetatable(t, v0_0_39_pings_mt)
end

local function new_v0_0_39_pings(meta, errors, warnings, pings)
	return cast_v0_0_39_pings({
		["meta"] = meta;
		["errors"] = errors;
		["warnings"] = warnings;
		["pings"] = pings;
	})
end

return {
	cast = cast_v0_0_39_pings;
	new = new_v0_0_39_pings;
}
