--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job class
local v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job = {}
local v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job_mt = {
	__name = "v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job";
	__index = v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job;
}

local function cast_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job_mt)
end

local function new_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job(set, infinite, Number_)
	return cast_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job;
	new = new_v0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_job;
}
