--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_openapi_meta_slurm class
local v0_0_40_openapi_meta_slurm = {}
local v0_0_40_openapi_meta_slurm_mt = {
	__name = "v0_0_40_openapi_meta_slurm";
	__index = v0_0_40_openapi_meta_slurm;
}

local function cast_v0_0_40_openapi_meta_slurm(t)
	return setmetatable(t, v0_0_40_openapi_meta_slurm_mt)
end

local function new_v0_0_40_openapi_meta_slurm(version, release, cluster)
	return cast_v0_0_40_openapi_meta_slurm({
		["version"] = version;
		["release"] = release;
		["cluster"] = cluster;
	})
end

return {
	cast = cast_v0_0_40_openapi_meta_slurm;
	new = new_v0_0_40_openapi_meta_slurm;
}
