--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_qos class
local v0_0_39_qos = {}
local v0_0_39_qos_mt = {
	__name = "v0_0_39_qos";
	__index = v0_0_39_qos;
}

local function cast_v0_0_39_qos(t)
	return setmetatable(t, v0_0_39_qos_mt)
end

local function new_v0_0_39_qos(description, flags, id, limits, name, preempt, priority, usage_factor, usage_threshold)
	return cast_v0_0_39_qos({
		["description"] = description;
		["flags"] = flags;
		["id"] = id;
		["limits"] = limits;
		["name"] = name;
		["preempt"] = preempt;
		["priority"] = priority;
		["usage_factor"] = usage_factor;
		["usage_threshold"] = usage_threshold;
	})
end

return {
	cast = cast_v0_0_39_qos;
	new = new_v0_0_39_qos;
}
