--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres class
local v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres = {}
local v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres_mt = {
	__name = "v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres";
	__index = v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres;
}

local function cast_v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres_mt)
end

local function new_v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres(allocated, requested)
	return cast_v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres({
		["allocated"] = allocated;
		["requested"] = requested;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres;
	new = new_v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_tres;
}
