--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_partition_info_defaults class
local v0_0_40_partition_info_defaults = {}
local v0_0_40_partition_info_defaults_mt = {
	__name = "v0_0_40_partition_info_defaults";
	__index = v0_0_40_partition_info_defaults;
}

local function cast_v0_0_40_partition_info_defaults(t)
	return setmetatable(t, v0_0_40_partition_info_defaults_mt)
end

local function new_v0_0_40_partition_info_defaults(memory_per_cpu, partition_memory_per_cpu, partition_memory_per_node, time, job)
	return cast_v0_0_40_partition_info_defaults({
		["memory_per_cpu"] = memory_per_cpu;
		["partition_memory_per_cpu"] = partition_memory_per_cpu;
		["partition_memory_per_node"] = partition_memory_per_node;
		["time"] = time;
		["job"] = job;
	})
end

return {
	cast = cast_v0_0_40_partition_info_defaults;
	new = new_v0_0_40_partition_info_defaults;
}
