--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_stats_rpc class
local v0_0_40_stats_rpc = {}
local v0_0_40_stats_rpc_mt = {
	__name = "v0_0_40_stats_rpc";
	__index = v0_0_40_stats_rpc;
}

local function cast_v0_0_40_stats_rpc(t)
	return setmetatable(t, v0_0_40_stats_rpc_mt)
end

local function new_v0_0_40_stats_rpc(rpc, count, time)
	return cast_v0_0_40_stats_rpc({
		["rpc"] = rpc;
		["count"] = count;
		["time"] = time;
	})
end

return {
	cast = cast_v0_0_40_stats_rpc;
	new = new_v0_0_40_stats_rpc;
}
