--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_diag_resp_statistics_bf_exit class
local v0_0_41_openapi_diag_resp_statistics_bf_exit = {}
local v0_0_41_openapi_diag_resp_statistics_bf_exit_mt = {
	__name = "v0_0_41_openapi_diag_resp_statistics_bf_exit";
	__index = v0_0_41_openapi_diag_resp_statistics_bf_exit;
}

local function cast_v0_0_41_openapi_diag_resp_statistics_bf_exit(t)
	return setmetatable(t, v0_0_41_openapi_diag_resp_statistics_bf_exit_mt)
end

local function new_v0_0_41_openapi_diag_resp_statistics_bf_exit(end_job_queue, bf_max_job_start, bf_max_job_test, bf_max_time, bf_node_space_size, state_changed)
	return cast_v0_0_41_openapi_diag_resp_statistics_bf_exit({
		["end_job_queue"] = end_job_queue;
		["bf_max_job_start"] = bf_max_job_start;
		["bf_max_job_test"] = bf_max_job_test;
		["bf_max_time"] = bf_max_time;
		["bf_node_space_size"] = bf_node_space_size;
		["state_changed"] = state_changed;
	})
end

return {
	cast = cast_v0_0_41_openapi_diag_resp_statistics_bf_exit;
	new = new_v0_0_41_openapi_diag_resp_statistics_bf_exit;
}
