--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_cluster_rec_associations class
local v0_0_39_cluster_rec_associations = {}
local v0_0_39_cluster_rec_associations_mt = {
	__name = "v0_0_39_cluster_rec_associations";
	__index = v0_0_39_cluster_rec_associations;
}

local function cast_v0_0_39_cluster_rec_associations(t)
	return setmetatable(t, v0_0_39_cluster_rec_associations_mt)
end

local function new_v0_0_39_cluster_rec_associations(root)
	return cast_v0_0_39_cluster_rec_associations({
		["root"] = root;
	})
end

return {
	cast = cast_v0_0_39_cluster_rec_associations;
	new = new_v0_0_39_cluster_rec_associations;
}
