--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_step_statistics class
local v0_0_40_step_statistics = {}
local v0_0_40_step_statistics_mt = {
	__name = "v0_0_40_step_statistics";
	__index = v0_0_40_step_statistics;
}

local function cast_v0_0_40_step_statistics(t)
	return setmetatable(t, v0_0_40_step_statistics_mt)
end

local function new_v0_0_40_step_statistics(CPU, energy)
	return cast_v0_0_40_step_statistics({
		["CPU"] = CPU;
		["energy"] = energy;
	})
end

return {
	cast = cast_v0_0_40_step_statistics;
	new = new_v0_0_40_step_statistics;
}
