--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job_array_response_msg_inner class
local v0_0_39_job_array_response_msg_inner = {}
local v0_0_39_job_array_response_msg_inner_mt = {
	__name = "v0_0_39_job_array_response_msg_inner";
	__index = v0_0_39_job_array_response_msg_inner;
}

local function cast_v0_0_39_job_array_response_msg_inner(t)
	return setmetatable(t, v0_0_39_job_array_response_msg_inner_mt)
end

local function new_v0_0_39_job_array_response_msg_inner(job_id, error_code, error, why)
	return cast_v0_0_39_job_array_response_msg_inner({
		["job_id"] = job_id;
		["error_code"] = error_code;
		["error"] = error;
		["why"] = why;
	})
end

return {
	cast = cast_v0_0_39_job_array_response_msg_inner;
	new = new_v0_0_39_job_array_response_msg_inner;
}
