--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_nodes_resp_last_update class
local v0_0_41_openapi_nodes_resp_last_update = {}
local v0_0_41_openapi_nodes_resp_last_update_mt = {
	__name = "v0_0_41_openapi_nodes_resp_last_update";
	__index = v0_0_41_openapi_nodes_resp_last_update;
}

local function cast_v0_0_41_openapi_nodes_resp_last_update(t)
	return setmetatable(t, v0_0_41_openapi_nodes_resp_last_update_mt)
end

local function new_v0_0_41_openapi_nodes_resp_last_update(set, infinite, Number_)
	return cast_v0_0_41_openapi_nodes_resp_last_update({
		["set"] = set;
		["infinite"] = infinite;
		["number"] = Number_;
	})
end

return {
	cast = cast_v0_0_41_openapi_nodes_resp_last_update;
	new = new_v0_0_41_openapi_nodes_resp_last_update;
}
