--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_job_mcs class
local v0_0_39_job_mcs = {}
local v0_0_39_job_mcs_mt = {
	__name = "v0_0_39_job_mcs";
	__index = v0_0_39_job_mcs;
}

local function cast_v0_0_39_job_mcs(t)
	return setmetatable(t, v0_0_39_job_mcs_mt)
end

local function new_v0_0_39_job_mcs(label)
	return cast_v0_0_39_job_mcs({
		["label"] = label;
	})
end

return {
	cast = cast_v0_0_39_job_mcs;
	new = new_v0_0_39_job_mcs;
}
