--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_39_assoc_usage class
local v0_0_39_assoc_usage = {}
local v0_0_39_assoc_usage_mt = {
	__name = "v0_0_39_assoc_usage";
	__index = v0_0_39_assoc_usage;
}

local function cast_v0_0_39_assoc_usage(t)
	return setmetatable(t, v0_0_39_assoc_usage_mt)
end

local function new_v0_0_39_assoc_usage(accrue_job_count, group_used_wallclock, fairshare_factor, fairshare_shares, normalized_priority, normalized_shares, effective_normalized_usage, normalized_usage, raw_usage, active_jobs, job_count, fairshare_level)
	return cast_v0_0_39_assoc_usage({
		["accrue_job_count"] = accrue_job_count;
		["group_used_wallclock"] = group_used_wallclock;
		["fairshare_factor"] = fairshare_factor;
		["fairshare_shares"] = fairshare_shares;
		["normalized_priority"] = normalized_priority;
		["normalized_shares"] = normalized_shares;
		["effective_normalized_usage"] = effective_normalized_usage;
		["normalized_usage"] = normalized_usage;
		["raw_usage"] = raw_usage;
		["active_jobs"] = active_jobs;
		["job_count"] = job_count;
		["fairshare_level"] = fairshare_level;
	})
end

return {
	cast = cast_v0_0_39_assoc_usage;
	new = new_v0_0_39_assoc_usage;
}
