--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily class
local v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily = {}
local v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily_mt = {
	__name = "v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily";
	__index = v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily;
}

local function cast_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily(t)
	return setmetatable(t, v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily_mt)
end

local function new_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily(count, last_run, duration)
	return cast_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily({
		["count"] = count;
		["last_run"] = last_run;
		["duration"] = duration;
	})
end

return {
	cast = cast_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily;
	new = new_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily;
}
