--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

-- v0_0_40_instance class
local v0_0_40_instance = {}
local v0_0_40_instance_mt = {
	__name = "v0_0_40_instance";
	__index = v0_0_40_instance;
}

local function cast_v0_0_40_instance(t)
	return setmetatable(t, v0_0_40_instance_mt)
end

local function new_v0_0_40_instance(cluster, extra, instance_id, instance_type, node_name, time)
	return cast_v0_0_40_instance({
		["cluster"] = cluster;
		["extra"] = extra;
		["instance_id"] = instance_id;
		["instance_type"] = instance_type;
		["node_name"] = node_name;
		["time"] = time;
	})
end

return {
	cast = cast_v0_0_40_instance;
	new = new_v0_0_40_instance;
}
