--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.api.slurmdb_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("slurmdb_api", function()
  local slurmrestapi_slurmdb_api = require "slurmrestapi.api.slurmdb_api"
  -- unit tests for slurmdb_v0040_delete_account
  describe("slurmdb_v0040_delete_account test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_delete_association
  describe("slurmdb_v0040_delete_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_delete_associations
  describe("slurmdb_v0040_delete_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_delete_cluster
  describe("slurmdb_v0040_delete_cluster test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_delete_single_qos
  describe("slurmdb_v0040_delete_single_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_delete_user
  describe("slurmdb_v0040_delete_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_delete_wckey
  describe("slurmdb_v0040_delete_wckey test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_account
  describe("slurmdb_v0040_get_account test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_accounts
  describe("slurmdb_v0040_get_accounts test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_association
  describe("slurmdb_v0040_get_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_associations
  describe("slurmdb_v0040_get_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_cluster
  describe("slurmdb_v0040_get_cluster test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_clusters
  describe("slurmdb_v0040_get_clusters test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_config
  describe("slurmdb_v0040_get_config test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_diag
  describe("slurmdb_v0040_get_diag test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_instance
  describe("slurmdb_v0040_get_instance test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_instances
  describe("slurmdb_v0040_get_instances test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_job
  describe("slurmdb_v0040_get_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_jobs
  describe("slurmdb_v0040_get_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_qos
  describe("slurmdb_v0040_get_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_single_qos
  describe("slurmdb_v0040_get_single_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_tres
  describe("slurmdb_v0040_get_tres test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_user
  describe("slurmdb_v0040_get_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_users
  describe("slurmdb_v0040_get_users test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_wckey
  describe("slurmdb_v0040_get_wckey test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_get_wckeys
  describe("slurmdb_v0040_get_wckeys test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_accounts
  describe("slurmdb_v0040_post_accounts test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_accounts_association
  describe("slurmdb_v0040_post_accounts_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_associations
  describe("slurmdb_v0040_post_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_clusters
  describe("slurmdb_v0040_post_clusters test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_config
  describe("slurmdb_v0040_post_config test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_qos
  describe("slurmdb_v0040_post_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_tres
  describe("slurmdb_v0040_post_tres test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_users
  describe("slurmdb_v0040_post_users test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_users_association
  describe("slurmdb_v0040_post_users_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0040_post_wckeys
  describe("slurmdb_v0040_post_wckeys test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_account
  describe("slurmdb_v0041_delete_account test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_association
  describe("slurmdb_v0041_delete_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_associations
  describe("slurmdb_v0041_delete_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_cluster
  describe("slurmdb_v0041_delete_cluster test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_single_qos
  describe("slurmdb_v0041_delete_single_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_user
  describe("slurmdb_v0041_delete_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_delete_wckey
  describe("slurmdb_v0041_delete_wckey test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_account
  describe("slurmdb_v0041_get_account test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_accounts
  describe("slurmdb_v0041_get_accounts test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_association
  describe("slurmdb_v0041_get_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_associations
  describe("slurmdb_v0041_get_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_cluster
  describe("slurmdb_v0041_get_cluster test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_clusters
  describe("slurmdb_v0041_get_clusters test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_config
  describe("slurmdb_v0041_get_config test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_diag
  describe("slurmdb_v0041_get_diag test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_instance
  describe("slurmdb_v0041_get_instance test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_instances
  describe("slurmdb_v0041_get_instances test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_job
  describe("slurmdb_v0041_get_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_jobs
  describe("slurmdb_v0041_get_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_qos
  describe("slurmdb_v0041_get_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_single_qos
  describe("slurmdb_v0041_get_single_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_tres
  describe("slurmdb_v0041_get_tres test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_user
  describe("slurmdb_v0041_get_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_users
  describe("slurmdb_v0041_get_users test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_wckey
  describe("slurmdb_v0041_get_wckey test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_get_wckeys
  describe("slurmdb_v0041_get_wckeys test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_accounts
  describe("slurmdb_v0041_post_accounts test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_accounts_association
  describe("slurmdb_v0041_post_accounts_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_associations
  describe("slurmdb_v0041_post_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_clusters
  describe("slurmdb_v0041_post_clusters test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_config
  describe("slurmdb_v0041_post_config test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_qos
  describe("slurmdb_v0041_post_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_tres
  describe("slurmdb_v0041_post_tres test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_users
  describe("slurmdb_v0041_post_users test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_users_association
  describe("slurmdb_v0041_post_users_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0041_post_wckeys
  describe("slurmdb_v0041_post_wckeys test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
