--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.api.slurm_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("slurm_api", function()
  local slurmrestapi_slurm_api = require "slurmrestapi.api.slurm_api"
  -- unit tests for slurm_v0039_cancel_job
  describe("slurm_v0039_cancel_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_delete_node
  describe("slurm_v0039_delete_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_diag
  describe("slurm_v0039_diag test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_job
  describe("slurm_v0039_get_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_jobs
  describe("slurm_v0039_get_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_node
  describe("slurm_v0039_get_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_nodes
  describe("slurm_v0039_get_nodes test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_partition
  describe("slurm_v0039_get_partition test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_partitions
  describe("slurm_v0039_get_partitions test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_reservation
  describe("slurm_v0039_get_reservation test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_get_reservations
  describe("slurm_v0039_get_reservations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_ping
  describe("slurm_v0039_ping test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_slurmctld_get_licenses
  describe("slurm_v0039_slurmctld_get_licenses test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_submit_job
  describe("slurm_v0039_submit_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_update_job
  describe("slurm_v0039_update_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0039_update_node
  describe("slurm_v0039_update_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_delete_job
  describe("slurm_v0040_delete_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_delete_jobs
  describe("slurm_v0040_delete_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_delete_node
  describe("slurm_v0040_delete_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_diag
  describe("slurm_v0040_get_diag test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_job
  describe("slurm_v0040_get_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_jobs
  describe("slurm_v0040_get_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_jobs_state
  describe("slurm_v0040_get_jobs_state test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_licenses
  describe("slurm_v0040_get_licenses test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_node
  describe("slurm_v0040_get_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_nodes
  describe("slurm_v0040_get_nodes test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_partition
  describe("slurm_v0040_get_partition test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_partitions
  describe("slurm_v0040_get_partitions test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_ping
  describe("slurm_v0040_get_ping test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_reconfigure
  describe("slurm_v0040_get_reconfigure test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_reservation
  describe("slurm_v0040_get_reservation test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_reservations
  describe("slurm_v0040_get_reservations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_get_shares
  describe("slurm_v0040_get_shares test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_post_job
  describe("slurm_v0040_post_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_post_job_submit
  describe("slurm_v0040_post_job_submit test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0040_post_node
  describe("slurm_v0040_post_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_delete_job
  describe("slurm_v0041_delete_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_delete_jobs
  describe("slurm_v0041_delete_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_delete_node
  describe("slurm_v0041_delete_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_diag
  describe("slurm_v0041_get_diag test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_job
  describe("slurm_v0041_get_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_jobs
  describe("slurm_v0041_get_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_jobs_state
  describe("slurm_v0041_get_jobs_state test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_licenses
  describe("slurm_v0041_get_licenses test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_node
  describe("slurm_v0041_get_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_nodes
  describe("slurm_v0041_get_nodes test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_partition
  describe("slurm_v0041_get_partition test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_partitions
  describe("slurm_v0041_get_partitions test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_ping
  describe("slurm_v0041_get_ping test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_reconfigure
  describe("slurm_v0041_get_reconfigure test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_reservation
  describe("slurm_v0041_get_reservation test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_reservations
  describe("slurm_v0041_get_reservations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_get_shares
  describe("slurm_v0041_get_shares test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_post_job
  describe("slurm_v0041_post_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_post_job_allocate
  describe("slurm_v0041_post_job_allocate test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_post_job_submit
  describe("slurm_v0041_post_job_submit test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurm_v0041_post_node
  describe("slurm_v0041_post_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_add_clusters
  describe("slurmdb_v0039_add_clusters test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_add_wckeys
  describe("slurmdb_v0039_add_wckeys test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_account
  describe("slurmdb_v0039_delete_account test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_association
  describe("slurmdb_v0039_delete_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_associations
  describe("slurmdb_v0039_delete_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_cluster
  describe("slurmdb_v0039_delete_cluster test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_qos
  describe("slurmdb_v0039_delete_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_user
  describe("slurmdb_v0039_delete_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_delete_wckey
  describe("slurmdb_v0039_delete_wckey test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_diag
  describe("slurmdb_v0039_diag test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_account
  describe("slurmdb_v0039_get_account test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_accounts
  describe("slurmdb_v0039_get_accounts test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_association
  describe("slurmdb_v0039_get_association test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_associations
  describe("slurmdb_v0039_get_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_cluster
  describe("slurmdb_v0039_get_cluster test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_clusters
  describe("slurmdb_v0039_get_clusters test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_config
  describe("slurmdb_v0039_get_config test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_job
  describe("slurmdb_v0039_get_job test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_jobs
  describe("slurmdb_v0039_get_jobs test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_qos
  describe("slurmdb_v0039_get_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_single_qos
  describe("slurmdb_v0039_get_single_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_tres
  describe("slurmdb_v0039_get_tres test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_user
  describe("slurmdb_v0039_get_user test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_users
  describe("slurmdb_v0039_get_users test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_wckey
  describe("slurmdb_v0039_get_wckey test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_get_wckeys
  describe("slurmdb_v0039_get_wckeys test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_set_config
  describe("slurmdb_v0039_set_config test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_update_accounts
  describe("slurmdb_v0039_update_accounts test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_update_associations
  describe("slurmdb_v0039_update_associations test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_update_qos
  describe("slurmdb_v0039_update_qos test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_update_tres
  describe("slurmdb_v0039_update_tres test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for slurmdb_v0039_update_users
  describe("slurmdb_v0039_update_users test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
