--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.model.v0_0_39_qos_limits_max_wall_clock
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v0_0_39_qos_limits_max_wall_clock", function()
  local slurmrestapi_v0_0_39_qos_limits_max_wall_clock = require "slurmrestapi.model.v0_0_39_qos_limits_max_wall_clock"

  -- unit tests for the property 'per'
  describe("property per test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
