--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.model.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned", function()
  local slurmrestapi_v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned = require "slurmrestapi.model.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned"

  -- unit tests for the property 'set'
  describe("property set test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'infinite'
  describe("property infinite test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'Number_'
  describe("property Number_ test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
