--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.model.v0_0_40_kill_jobs_resp_job_error
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v0_0_40_kill_jobs_resp_job_error", function()
  local slurmrestapi_v0_0_40_kill_jobs_resp_job_error = require "slurmrestapi.model.v0_0_40_kill_jobs_resp_job_error"

  -- unit tests for the property 'String_'
  describe("property String_ test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'code'
  describe("property code test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'message'
  describe("property message test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
