--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.model.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly", function()
  local slurmrestapi_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly = require "slurmrestapi.model.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly"

  -- unit tests for the property 'count'
  describe("property count test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'last_run'
  describe("property last_run test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'duration'
  describe("property duration test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
