--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.model.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration", function()
  local slurmrestapi_v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration = require "slurmrestapi.model.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration"

  -- unit tests for the property 'last'
  describe("property last test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'max'
  describe("property max test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'time'
  describe("property time test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
