--[[
  Slurm REST API

  API to access and control Slurm

  The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
  Contact: sales@schedmd.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for slurmrestapi.model.v0_0_41_openapi_partition_resp_partitions_inner_maximums
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("v0_0_41_openapi_partition_resp_partitions_inner_maximums", function()
  local slurmrestapi_v0_0_41_openapi_partition_resp_partitions_inner_maximums = require "slurmrestapi.model.v0_0_41_openapi_partition_resp_partitions_inner_maximums"

  -- unit tests for the property 'cpus_per_node'
  describe("property cpus_per_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'cpus_per_socket'
  describe("property cpus_per_socket test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'memory_per_cpu'
  describe("property memory_per_cpu test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'partition_memory_per_cpu'
  describe("property partition_memory_per_cpu test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'partition_memory_per_node'
  describe("property partition_memory_per_node test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'nodes'
  describe("property nodes test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'shares'
  describe("property shares test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'oversubscribe'
  describe("property oversubscribe test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'time'
  describe("property time test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'over_time_limit'
  describe("property over_time_limit test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
